;;; private/rschmukler/theming.el -*- lexical-binding: t; -*-

;; (setq neo-theme 'icons)
(doom-themes-neotree-config)
(setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
      doom-themes-enable-italic t) ; if nil, italics is universally disabled
(doom-themes-org-config)

(defun rs/reload-theme-in-all-frames ()
  "Function to force the reloading of the active theme in all frames.
   To be called from emacsclient after modifying the theme file"
  (dolist (frame (visible-frame-list))
    (with-selected-frame frame (doom/reload-theme))))

(defun rs/initialize-theming ()
  (when (window-system)
    (add-to-list 'default-frame-alist '(alpha . (95)))
    (set-frame-parameter (selected-frame) 'alpha '(95)))
  (when (eq system-type 'darwin)
    (ns-auto-titlebar-mode)
    (set-face-attribute 'default nil
                        :family "mononoki"
                        :height 140
                        :weight 'normal
                        :width 'normal)
    (load-theme 'doom-dream-gradient t))
  (when (eq system-type 'gnu/linux)
    (set-face-attribute 'default nil
                        :family "mononoki"
                        :height 80
                        :weight 'normal
                        :width 'normal)
    (load-theme 'wpg-autogenerated t)))

(cond
 ((window-system) (rs/initialize-theming))
 ((daemonp) (add-hook 'after-make-frame-functions
                      '(lambda (frame)
                         (with-selected-frame frame
                           (rs/initialize-theming))))))

(setq +ivy-buffer-icons t)

;; (require 'color)
;; (set-face-attribute 'org-block nil :background
;; (color-darken-name
;; (face-attribute 'default :background) 1))
;; (set-face-attribute 'org-block-begin-line nil :background (face-attribute 'default :background))
;; (set-face-attribute 'org-block-end-line nil :background (face-attribute 'default :background))
(set-face-attribute 'org-level-1 nil :background
                    (doom-darken (face-attribute 'default :background) 0.15))
