;; -*- no-byte-compile: t; -*-
;;; private/rschmukler/packages.el

(package! flycheck)
(package! flycheck-mix)
(package! flycheck-credo)
(package! all-the-icons-ivy)
(package! lux-mode :recipe (:fetcher github :repo "LuxLang/lux" :files ("lux-mode/*")))
(package! cider)
(package! paredit)
(package! clojure-mode)
(package! flycheck-clojure)
(package! erlang)
(package! racket-mode)
(package! geiser)
(package! graphql-mode)
(package! rust-mode)
(package! racer)
(package! flycheck-rust)
(package! intero)
(package! org)
